name: AntiCheat
main: xyz.acrylicstyle.anticheat.AntiCheatPlugin
version: 0.0.4
depend:
  - TomeitoLib
commands:
  ac:
    aliases: ["anticheat"]
permissions:
  anticheat.bypass:
    description: "Bypasses anti-cheat checks or not"
    default: op